### ISSUE TITLE
javafx.web module: how to add it?

### ISSUE THREAD

**Issue by elifarley** [beryx-gist/badass-jlink-example-kotlin-tornadofx#2]
I need to `import javafx.scene.web.WebView`, which lives in the `javafx.web` module, but it gives me this error:
```
gradle jlinkZip
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.0/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
Found module name 'myapp.desktop.mod'

> Task :discoverMainScriptsExtensions
e: Module javafx.web cannot be found in the module graph
> Task :compileKotlin FAILED
```

Thank you!

**Comment by siordache** [comment]
You need to add `javafx.web` to the list of javafx modules:
```
javafx {
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.web")
}
```

I updated the [badass-jlink-example-kotlin-javafx](https://github.com/beryx-gist/badass-jlink-example-kotlin-javafx) example to display the 'Hello, world!' text in a WebView.

**Comment by elifarley** [comment]
Thank you!

Now, I have another problem, but this is due to my dependencies not being modularized yet:

```
/build/jlinkbase/tmpjars/java-multiaddr-v1.3.0/module-info.java:2: error: '{' expected
open module java-multiaddr-v1.3.0 {
                ^
1 error
> Task :createDelegatingModules FAILED
```
I'll try to use beryx/badass-runtime-plugin instead.

**Comment by siordache** [comment]
`java-multiaddr-v1.3.0` is not a [valid module name](https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-7.7):
> A module name consists of one or more Java identifiers (§3.8) separated by "." tokens.

**Comment by elifarley** [comment]
Yep, to fix it, I created a PR on the java-multiaddr repo: multiformats/java-multiaddr#14
